package:
  name: argo-workflows-3.7
  version: "3.7.2"
  epoch: 1
  description: Workflow engine for Kubernetes.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - argo-workflows=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - node-gyp
      - nodejs-20
      - openssl
      - yarn
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cf605b548f1b0137836dde2032517707ba87c6ae
      repository: https://github.com/argoproj/argo-workflows
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        github.com/go-viper/mapstructure/v2@v2.4.0

  - uses: patch
    with:
      patches: remedieate-cve-bump-ui-dependencies.patch

  - name: Generate yarn UI
    runs: |
      rm -rf ui/.yarnrc ui/yarn.lock
      JOBS=max yarn --cwd ui install
      JOBS=max yarn --cwd ui build

      # Install staticfiles for build time
      go install bou.ke/staticfiles@dd04075
      # Pack yarn UI into go binary
      /home/build/.cache/go/bin/staticfiles -o server/static/files.go ui/dist/app

  - uses: go/build
    with:
      packages: ./cmd/argo
      output: argo
      ldflags: |
        -X github.com/argoproj/argo-workflows/v3.version=$(git describe --exact-match --tags --abbrev=0  2> /dev/null || echo untagged)
        -X github.com/argoproj/argo-workflows/v3.buildDate=$(date -u ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
        -X github.com/argoproj/argo-workflows/v3.gitCommit=$(git rev-parse HEAD || echo unknown)
        -X github.com/argoproj/argo-workflows/v3.gitTreeState=$(if [ -z "`git status --porcelain`" ]; then echo "clean" ; else echo "dirty"; fi)

  - uses: strip

subpackages:
  - name: argo-workflows-known-hosts-${{vars.major-minor-version}}
    description: "known hosts file for argo workflows"
    dependencies:
      provides:
        - argo-workflows-known-hosts=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/ssh
          cp hack/ssh_known_hosts ${{targets.subpkgdir}}/etc/ssh/
      - uses: strip

  - name: argo-workflow-controller-${{vars.major-minor-version}}
    description: "Argo workflow controller"
    dependencies:
      provides:
        - argo-workflow-controller=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/workflow-controller
          output: workflow-controller
          ldflags: |
            -X github.com/argoproj/argo-workflows/v3.version=$(git describe --exact-match --tags --abbrev=0  2> /dev/null || echo untagged)
            -X github.com/argoproj/argo-workflows/v3.buildDate=$(date -u ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
            -X github.com/argoproj/argo-workflows/v3.gitCommit=$(git rev-parse HEAD || echo unknown)
            -X github.com/argoproj/argo-workflows/v3.gitTreeState=$(if [ -z "`git status --porcelain`" ]; then echo "clean" ; else echo "dirty"; fi)
      - uses: strip
    test:
      pipeline:
        - runs: |
            workflow-controller version
            workflow-controller --help

  - name: argo-workflow-controller-${{vars.major-minor-version}}-compat
    dependencies:
      runtime:
        - argo-workflow-controller-${{vars.major-minor-version}}
      provides:
        - argo-workflow-controller-compat=${{package.full-version}}
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/workflow-controller ${{targets.subpkgdir}}/workflow-controller

  - name: argo-workflow-executor-${{vars.major-minor-version}}
    description: "Argo workflow executor"
    dependencies:
      provides:
        - argo-workflow-executor=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/argoexec
          output: argoexec
          ldflags: |
            -X github.com/argoproj/argo-workflows/v3.version=$(git describe --exact-match --tags --abbrev=0  2> /dev/null || echo untagged)
            -X github.com/argoproj/argo-workflows/v3.buildDate=$(date -u ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
            -X github.com/argoproj/argo-workflows/v3.gitCommit=$(git rev-parse HEAD || echo unknown)
            -X github.com/argoproj/argo-workflows/v3.gitTreeState=$(if [ -z "`git status --porcelain`" ]; then echo "clean" ; else echo "dirty"; fi)
      - uses: strip
    test:
      pipeline:
        - runs: |
            argoexec version
            argoexec --help

  - name: argo-workflow-executor-${{vars.major-minor-version}}-compat
    dependencies:
      provides:
        - argo-workflow-executor-compat=${{package.full-version}}
      runtime:
        - argo-workflow-executor-${{vars.major-minor-version}}
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/argoexec ${{targets.subpkgdir}}/argoexec

  - name: argo-workflow-cli-${{vars.major-minor-version}}
    dependencies:
      provides:
        - argo-workflow-cli=${{package.full-version}}
      runtime:
        - argo-workflows-${{vars.major-minor-version}}
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          # Argocli serves the server https://github.com/argoproj/argo-workflows/blob/master/Dockerfile#L110
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/argo ${{targets.subpkgdir}}/argo

  - name: argo-workflows-ui-${{vars.major-minor-version}}
    description: "Argo workflows embedded UI"
    dependencies:
      provides:
        - argo-workflows-ui=${{package.full-version}}
      runtime:
        - esbuild
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui
          cp -ar ui/ ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui
          # Remove musl-linked prebuilt binaries.
          rm -rf "${{targets.subpkgdir}}"/usr/lib/argo-workflows-ui/ui/node_modules/@parcel/watcher-linux-*-musl/
      # Mitigate CVE-2025-22866
      - assertions:
          required-steps: 1
        pipeline:
          - if: ${{build.arch}} == "x86_64"
            runs: |
              rm ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui/ui/node_modules/@esbuild/linux-x64/bin/esbuild
              ln -sf /usr/bin/esbuild ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui/ui/node_modules/@esbuild/linux-x64/bin/esbuild
          - if: ${{build.arch}} == "aarch64"
            runs: |
              rm ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui/ui/node_modules/@esbuild/linux-arm64/bin/esbuild
              ln -sf /usr/bin/esbuild ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui/ui/node_modules/@esbuild/linux-arm64/bin/esbuild

update:
  enabled: true
  github:
    identifier: argoproj/argo-workflows
    strip-prefix: v
    tag-filter: v3.7.

test:
  environment:
    contents:
      packages:
        - argo-workflow-cli-${{vars.major-minor-version}}
        - argo-workflow-controller-${{vars.major-minor-version}}-compat
        - argo-workflow-controller-${{vars.major-minor-version}}
        - argo-workflow-executor-${{vars.major-minor-version}}-compat
        - argo-workflow-executor-${{vars.major-minor-version}}
  pipeline:
    - runs: |
        # Test compat packages and full paths
        /usr/bin/argo --help
        /usr/bin/argoexec --help
        /usr/bin/workflow-controller --help
        /argo --help
        /workflow-controller --help
        /argoexec --help
