package:
  name: crun
  version: "1.16"
  epoch: 0
  description: "Fast and lightweight fully featured OCI runtime and C library for running containers"
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go-md2man
      - libcap-dev
      - libseccomp
      - libseccomp-dev
      - python3
      - wolfi-base
      - yajl
      - yajl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/containers/crun/releases/download/${{package.version}}/crun-${{package.version}}.tar.gz
      expected-sha512: 718e17abdb8c2a9e1fdd39f09e7e3e435d88c5785cc13c1e67f492847d7d938cf399aecc055ecf88720fa8f73b8539f057e3b0e53f10f4e382f5664a2243b959

  - runs: |
      ./configure \
         --prefix=/usr \
         --disable-systemd

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: crun-doc
    pipeline:
      - uses: split/manpages
    description: crun manpages

update:
  enabled: true
  release-monitor:
    identifier: 96792
