package:
  name: grafana-9.5
  version: 9.5.15
  epoch: 0
  description: The open and composable observability and data visualization platform.
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - bash

environment:
  contents:
    packages:
      - build-base
      - busybox
      - findutils
      - go
      - nodejs-18
      - posix-libc-utils
      - py3-setuptools
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/grafana
      tag: v${{package.version}}
      expected-commit: 5f5a096c79a0200a4a2cddbb499c50095edc3401

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/elazarl/goproxy@v0.0.0-20231117061959-7cc037d33fb5 github.com/go-jose/go-jose/v3@v3.0.1 go.opentelemetry.io/otel@v1.21.0 go.opentelemetry.io/otel/trace@v1.21.0 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel/sdk@v1.21.0 github.com/go-git/go-git/v5@v5.11.0

  - runs: |
      yarn install
      yarn run build
      yarn run plugins:build-bundled

      # Our default LDFLAGS cause an issue with grafana. We need to remove '-z, noexecheap' from LDFLAGS
      # Ref https://github.com/wolfi-dev/os/issues/7419
      LDFLAGS="$(echo $LDFLAGS | sed 's/,-z,noexecheap//g')"
      make build

      mkdir -p ${{targets.destdir}}/usr/bin
      mv ./bin/linux-*/* ${{targets.destdir}}/usr/bin/

  - name: package
    runs: |
      mkdir -p ${{targets.destdir}}/usr/share/grafana/plugins-bundled
      mkdir -p ${{targets.destdir}}/usr/share/grafana/scripts
      mkdir -p ${{targets.destdir}}/usr/share/grafana/bin

      mv ./conf ${{targets.destdir}}/usr/share/grafana/
      mv ./plugins-bundled/internal ${{targets.destdir}}/usr/share/grafana/plugins-bundled/
      mv ./public ${{targets.destdir}}/usr/share/grafana/
      mv ./scripts/*.sh ${{targets.destdir}}/usr/share/grafana/scripts/

      mkdir -p ${{targets.destdir}}/etc/grafana/
      cp ${{targets.destdir}}/usr/share/grafana/conf/sample.ini ${{targets.destdir}}/etc/grafana/grafana.ini

subpackages:
  - name: grafana-oci-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/grafana
          mv ./packaging/docker/run.sh ${{targets.subpkgdir}}/opt/grafana/

update:
  enabled: true
  github:
    identifier: grafana/grafana
    strip-prefix: v
    tag-filter: v9.5
