package:
  name: pulumi-language-java
  version: 0.14.0
  epoch: 0
  description: Pulumi Language SDK for Java
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1479147de7bcdd4c8ae04919cd1965f07b81f7df
      repository: https://github.com/pulumi/pulumi-java.git
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/pulumi/pulumi-java/pkg/version.Version=v${{package.version}}
      modroot: pkg
      output: pulumi-language-java
      packages: ./cmd/pulumi-language-java

  - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-java
    strip-prefix: v
