# NOTE: This is not a complete rancher-2.9 package with all the components.
# This is just created for the purpose of building the rancher-agent package.
vars:
  LOGLEVEL_VERSION: 0.1.6

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

package:
  name: rancher-2.9
  version: 2.9.0
  epoch: 2
  description: Complete container management platform
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher=${{package.full-version}}

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates
      - go
      - perl-utils
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/rancher
      tag: v${{package.version}}
      expected-commit: 9e0cc54e7e3a924cf0ed5c5d4db0a6e53805c75e

subpackages:
  - name: rancher-agent-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-agent=${{package.full-version}}
      runtime:
        - kubectl
        - tini
        - rancher-kontainer-driver-metadata-${{vars.major-minor-version}}
        - rancher-system-charts-${{vars.major-minor-version}}
        - rancher-partner-charts-${{vars.major-minor-version}}
        - rancher-charts-${{vars.major-minor-version}}
        - rancher-loglevel-${{vars.major-minor-version}}
        - rancher-rke2-charts-${{vars.major-minor-version}}
        - rancher-helm3-charts-${{vars.major-minor-version}}
        - util-linux-misc # unshare
        - mount
        - umount
        - busybox # nsenter
        - util-linux-dev
        - jq
        - gzip
        - gawk
        - bash
        - sysstat
        - acl-dev
        - vim
        - iproute2
        - net-tools
        - openssh-client
        - busybox
        - posix-libc-utils
        - curl
        - openssl
    pipeline:
      - uses: go/bump
        with:
          deps: github.com/go-jose/go-jose/v3@v3.0.3 k8s.io/kubernetes@v1.30.3 k8s.io/apiserver@v0.30.3
      - uses: go/build
        with:
          packages: ./cmd/agent
          output: agent
          ldflags: |
            -X main.VERSION=${{package.version}}
          tags: k8s
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/bin
          install -Dm755 package/run.sh ${{targets.contextdir}}/usr/bin/
          install -Dm755 package/kubectl-shell.sh ${{targets.contextdir}}/usr/bin/
          install -Dm755 package/shell-setup.sh ${{targets.contextdir}}/usr/bin/
    test:
      pipeline:
        - runs: |
            agent | grep "Rancher agent version ${{package.version}}"

  - name: rancher-kontainer-driver-metadata-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-kontainer-driver-metadata=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/kontainer-driver-metadata/
          branch: release-v${{vars.major-minor-version}}
          expected-commit: 8bdffff5b7271f8e5cb9d148ae25c1c3192b62b6
          destination: kontainer-driver-metadata
      - working-directory: ./kontainer-driver-metadata
        runs: |
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata
          install -Dm755 data/data.json  ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata/data.json
    test:
      pipeline:
        - runs: |
            # check the expected files are available at the expected location at `/var/lib/rancher-data/driver-metadata/`
            test -f /var/lib/rancher-data/driver-metadata/data.json

  - name: rancher-system-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-system-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/system-charts
          branch: release-v${{vars.major-minor-version}}
          destination: system-charts
          expected-commit: 653a0337600f04df3a975106468a17bd64d6e1f9
      - working-directory: ./system-charts
        runs: |
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/system-library
          cp -r ./*  ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/system-library
    test:
      pipeline:
        - runs: |
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/system-library/`
            test -f /var/lib/rancher-data/local-catalogs/system-library/README.md

  - name: rancher-partner-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-partner-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/partner-charts
          branch: main
          destination: partner-charts
          expected-commit: e95ababa2c9a41b8a974752157646a5013ea0f4d
      - working-directory: ./partner-charts
        runs: |
          shasum256=$(echo -n "https://git.rancher.io/partner-charts" |shasum -a 256 | awk '{ print $1 }')
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256
    test:
      environment:
        contents:
          packages:
            - perl-utils
      pipeline:
        - runs: |
            shasum256=$(echo -n "https://git.rancher.io/partner-charts" |shasum -a 256 | awk '{ print $1 }')
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256/`
            test -f /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/$shasum256/README.md

  - name: rancher-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/charts
          branch: release-v${{vars.major-minor-version}}
          destination: charts
          expected-commit: bfa3b06d877703e24c94f62187cdfce3cdbb2c67
          depth: -1
      - working-directory: ./charts
        runs: |
          shasum256=$(echo -n "https://git.rancher.io/charts" |shasum -a 256 | awk '{ print $1 }')
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256
      - working-directory: ./charts
        runs: |
          git checkout master
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/library
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/library
    test:
      environment:
        contents:
          packages:
            - perl-utils
      pipeline:
        - runs: |
            shasum256=$(echo -n "https://git.rancher.io/charts" |shasum -a 256 | awk '{ print $1 }')
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256/`
            test -f /var/lib/rancher-data/local-catalogs/v2/rancher-charts/$shasum256/README.md
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/library/`
            test -f /var/lib/rancher-data/local-catalogs/library/README.md

  - name: rancher-rke2-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-rke2-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/rke2-charts
          branch: main
          destination: rke2-charts
          expected-commit: 0f967664cd95614fc06646eb1fb49b9346b1dbcb
      - working-directory: ./rke2-charts
        runs: |
          shasum256=$(echo -n "https://git.rancher.io/rke2-charts" |shasum -a 256 | awk '{ print $1 }')
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256
    test:
      environment:
        contents:
          packages:
            - perl-utils
      pipeline:
        - runs: |
            shasum256=$(echo -n "https://git.rancher.io/rke2-charts" |shasum -a 256 | awk '{ print $1 }')
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256/`
            test -f /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/$shasum256/README.md

  - name: rancher-helm3-charts-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-helm3-charts=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          repository: https://github.com/rancher/helm3-charts
          branch: master
          destination: helm3-charts
          expected-commit: c6986e9372b206e9c93f4d53de5a8fa46f210960
      - working-directory: ./helm3-charts
        runs: |
          mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/helm3-library
          cp -r ./* ${{targets.contextdir}}/var/lib/rancher-data/local-catalogs/helm3-library
    test:
      pipeline:
        - runs: |
            # check the expected files are available at the expected location at `/var/lib/rancher-data/local-catalogs/helm3-library/`
            test -f /var/lib/rancher-data/local-catalogs/helm3-library/README.md

  - name: rancher-loglevel-${{vars.major-minor-version}}
    dependencies:
      provides:
        - rancher-loglevel=${{package.full-version}}
    pipeline:
      - uses: git-checkout
        with:
          expected-commit: 467a3f813c0a5f988fd1be76545ed28af15d9afc
          repository: https://github.com/rancher/loglevel
          tag: v${{vars.LOGLEVEL_VERSION}}
          destination: loglevel
      - uses: go/build
        with:
          ldflags: -X main.Version={{package.version}}
          modroot: loglevel
          output: loglevel
          packages: .
    test:
      pipeline:
        - runs: |
            loglevel -v

update:
  enabled: true
  github:
    identifier: rancher/rancher
    strip-prefix: v
    use-tag: true
    tag-filter: v2.9.
