package:
  name: strongswan
  version: 5.9.14
  epoch: 0
  description: "strongSwan - IPsec-based VPN"
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf-archive
      - bison
      - build-base
      - busybox
      - flex
      - gmp-dev
      - openssl-dev
      - gperf
      - libtool
      - ltrace
      - perl
      - pkgconf-dev
  environment:
    CFLAGS: -Wno-error=calloc-transposed-args

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/strongswan/strongswan
      tag: ${{package.version}}
      expected-commit: dea8493f3a6a5ef16ee97d0d446ca52f8f8afa3c

  # Add m4_pattern_allow to allow the use of AC_LIB_PREFIX macro.
  # Build fails on first attempt (but succeeds on subsequent), without this.
  - runs: |
      sed -i '1im4_pattern_allow([AC_LIB_PREFIX])' configure.ac

  # Reference (not an official container image):
  # - https://github.com/strongX509/docker/blob/master/strongswan/Dockerfile
  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --disable-defaults \
        --enable-charon \
        --enable-ikev2 \
        --enable-nonce \
        --enable-random \
        --enable-openssl \
        --enable-pem \
        --enable-x509 \
        --enable-pubkey \
        --enable-constraints \
        --enable-pki \
        --enable-socket-default \
        --enable-kernel-netlink \
        --enable-swanctl \
        --enable-resolve \
        --enable-eap-identity \
        --enable-eap-md5 \
        --enable-eap-dynamic \
        --enable-eap-tls \
        --enable-updown \
        --enable-vici \
        --enable-silent-rules

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    pipeline:
      # https://github.com/strongX509/docker/blob/master/strongswan/Dockerfile#L27C10-L27C35
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/libexec/ipsec/charon ${{targets.subpkgdir}}/charon

update:
  enabled: true
  github:
    identifier: strongswan/strongswan
    use-tag: true
  ignore-regex-patterns:
    - '.*android.*'
    - '.*beta.*'
    - '.*rc.*'
    - '.*dr.*'

test:
  pipeline:
    - name: "Basic version checks"
      runs: |
        swanctl --help
