package:
  name: strongswan
  version: 5.9.14
  epoch: 0
  description: "strongSwan - IPsec-based VPN"
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf-archive
      - bison
      - build-base
      - busybox
      - curl-dev
      - flex
      - gmp-dev
      - libgcrypt-dev
      - sqlite-dev
      - linux-headers
      - libcap-ng-dev
      - libcap-dev
      - libedit-dev
      - libidn-dev
      - libxml2-dev
      - openssl-dev
      - gperf
      - libtool
      - ltrace
      - perl
      - pkgconf-dev
  environment:
    CFLAGS: -Wno-error=calloc-transposed-args

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/strongswan/strongswan
      tag: ${{package.version}}
      expected-commit: dea8493f3a6a5ef16ee97d0d446ca52f8f8afa3c

  - runs: |
      sed -i '1im4_pattern_allow([AC_LIB_PREFIX])' configure.ac
      mkdir -p "${{targets.destdir}}/etc/strongswan.d/charon"

  # Drew inspiration here from how other distros had packaged this.
  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --libexecdir=/usr/libexec \
        --enable-conf \
        --enable-charon \
        --enable-swanctl \
        --enable-stroke \
        --enable-openssl \
        --enable-gmp \
        --enable-gcrypt \
        --enable-sql \
        --enable-sqlite \
        --enable-dhcp \
        --enable-curl \
        --enable-kernel-libipsec \
        --enable-kernel-netlink \
        --enable-addrblock \
        --enable-ccm \
        --enable-cmac \
        --enable-ctr \
        --enable-eap-identity \
        --enable-eap-md5 \
        --enable-eap-mschapv2 \
        --enable-eap-radius \
        --enable-eap-tls \
        --enable-eap-ttls \
        --enable-farp \
        --enable-gcm \
        --enable-hmac \
        --enable-md4 \
        --enable-md5 \
        --enable-random \
        --enable-sha1 \
        --enable-sha2 \
        --enable-unity \
        --enable-updown \
        --enable-vici \
        --enable-silent-rules

  - uses: autoconf/make

  - uses: autoconf/make-install

  # When running `charon`, we are running into errors such as:
  # feature CUSTOM:libcharon-receiver in critical plugin 'charon' has unmet dependency: HASHER:HASH_SHA1
  # Which indicate missing plugins or configurations. The plugins are definitely installed, however some
  # of the .conf files don't appear to be getting copied into place by the build? This is my 'attempt'
  # at doing so.
  #
  # However, those .conf files are.. empty... why? No idea. Perhaps we do NOT need to do this at all,
  # and we need to provide our own /conf files? basically, make 'charon' work.
  #
  - runs: |
      # Copy the main configuration file
      cp conf/strongswan.conf "${{targets.destdir}}/etc/strongswan.conf"

      # Copy all plugin configuration files
      cp conf/plugins/*.conf "${{targets.destdir}}/etc/strongswan.d/charon/"
  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          ln -sf /usr/libexec/ipsec/charon ${{targets.subpkgdir}}/usr/bin/charon

update:
  enabled: true
  github:
    identifier: strongswan/strongswan
    use-tag: true
  ignore-regex-patterns:
    - '.*android.*'
    - '.*beta.*'
    - '.*rc.*'
    - '.*dr.*'

test:
  pipeline:
    - name: "Basic version checks"
      runs: |
        ipsec --help
        ipsec --version
        swanctl --help
    - name: "Check 'ipsec version' returns strongSwan"
      runs: |
        ipsec version > /tmp/strongswan-version.log 2>&1

        if grep -q "Linux strongSwan" /tmp/strongswan-version.log; then
          echo "Test passed: Found 'Linux strongSwan' in version output."
        else
          echo "Test failed: 'Linux strongSwan' not found in version output."
          cat /tmp/strongswan-version.log
          exit 1
        fi
