package:
  name: strongswan
  version: 5.9.14
  epoch: 1
  description: "strongSwan - IPsec-based VPN"
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf-archive
      - bison
      - build-base
      - busybox
      - flex
      - gmp-dev
      - gperf
      - libtool
      - ltrace
      - perl
      - pkgconf-dev
  environment:
    CFLAGS: -Wno-error=calloc-transposed-args

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/strongswan/strongswan
      tag: ${{package.version}}
      expected-commit: dea8493f3a6a5ef16ee97d0d446ca52f8f8afa3c

  # Add m4_pattern_allow to allow the use of AC_LIB_PREFIX macro.
  # Build fails on first attempt (but succeeds on subsequent), without this.
  - runs: |
      sed -i '1im4_pattern_allow([AC_LIB_PREFIX])' configure.ac

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: strongswan/strongswan
    use-tag: true
  ignore-regex-patterns:
    - '.*android.*'
    - '.*beta.*'
    - '.*rc.*'
    - '.*dr.*'

# TODO - these basic tests DO NOT validate this applications functionality.
# We need some level of functional testing.
#
# ******** If you are reading this comment in a PR - Reject this PR ********
# ******** The person has not taken the time to properly test this. ********
test:
  pipeline:
    - name: "Basic version checks"
      runs: |
        ipsec --help
        ipsec --version
        swanctl --help
    - name: "Check 'ipsec version' returns strongSwan"
      runs: |
        ipsec version > /tmp/strongswan-version.log 2>&1

        if grep -q "Linux strongSwan" /tmp/strongswan-version.log; then
          echo "Test passed: Found 'Linux strongSwan' in version output."
        else
          echo "Test failed: 'Linux strongSwan' not found in version output."
          cat /tmp/strongswan-version.log
          exit 1
        fi
